<?php

		switch(@mysql_real_escape_string($_GET['aka'])){
		default:
		
		
		
		
		break;
		case'icari':
		include"icari_mini.php";
		break;
		case'icari_full':
		include"icari.php";
		break;
		case'g_active':
		include"g_active.php";
		break;
		case'icari_nim':
		include"icari_nim.php";
		break;
		case'ikonversi':
		include"ikonversi.php";
		break;
		case'vprofil_dosen':
		include"vprofil_dosen.php";
		break;
		case'icari3':
		include"icari3.php";
		break;
		case'icari2':
		include"icari2.php";
		break;
		case'i_profil_mahasiswa':
		include"i_profil_mahasiswa.php";
		break;
		case'presensi':
		include"vsks.php";
		break;
		case'csks':
		include"csks.php";
		break;
		case'menu_batas_nilai':
		include"menu_batas_nilai.php";
		break;
		case'mkuis':
		include"mkuis.php";
		break;
		case'ikurikulum':
		include"i_kurikulum.php";
		break;
		case'vkurikulum':
		include"vkurikulum.php";
		break;
		case'ckurikulum':
		include"ckurikulum.php";
		break;
		case'edit_kurikulum':
		include"edit_kurikulum.php";
		break;
		case'vsks2':
		include"vsks2.php";
		break;
		case'belumkrs':
		include"rekap.php";
		break;
		case'csks':
	  include"csks.php";
	  break;
	  case'vsks':
	  include"vsks.php";
	  break;
	  case'idosen':
	  include"iprofil_dosen.php";
	  break;
	   case'eakun':
	  include"eakun.php";
	  break;
	  case'edit_sks':
	  include"edit_sks.php";
	  break;
	 //update
	  case'update_sks':
	  include"SKS_UPDATE_KURIKULUM.php";
	  //include"edit_sks.php";
	  break;
		case'imahasiswa':
	  include"imahasiswa.php";
	  break;
	  case'iudosen':
	  include"idosen.php";
	  break;
	   case'sroom':
	  include"sroom.php";
	  break;
	  case'icari4':
	  include"icari4.php";
	  break;
		case'ikonversi_global':
	  include"ikonversi_global.php";
	  break;
	  case'ikonversi_kejuruan':
	  include"ikonversi_kejuruan.php";
	  break;
	  case'vsks_kuis':
	  include"vsks_kuis.php";
	  break;
	  case'edit_kuis':
	  include"edit_kuis.php";
	  break;
		case'vbiaya_global':
	  include"mbiaya.php";
	  break;
		  case'vtranskrip':
	  include"icari2transkrip.php";
	  break;
	 case'icari4transkrip':
	  include"icari4transkrip.php";
	  break;
		case'icari_krs':
		include"icari_krs.php";
		break;
	case'CARI_PERIODE_CETAK':
		include"CARI_PERIODE_CETAK.php";
	break;
	case'IMPORT_NO_IJASAH':
		include"IMPORT_NO_IJASAH.php";
	break;
	case'icari_ipk_progdi':
		//include"icari_ipk_nim.php";
		include"icari_ipk_progdi.php";
	break;
	case'icari_ipk_nim':
		//include"icari_ipk_nim.php";
		include"icari_ipk_progdi.php";
	break;
		case'iwisuda':
	  include"m1a2h3a4s5i6s7w8a/index.php";
	  break;
		}
?>